
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package pl6;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PTOYCOMA = 18;
  public static final int PROCEDURE = 10;
  public static final int DOSPUNTOS = 16;
  public static final int CIERRACOR = 15;
  public static final int CHAR = 4;
  public static final int ABREPAR = 12;
  public static final int ID = 19;
  public static final int OF = 9;
  public static final int NUM = 20;
  public static final int CARACTER = 11;
  public static final int BOOLEAN = 5;
  public static final int COMA = 17;
  public static final int CIERRAPAR = 13;
  public static final int EOF = 0;
  public static final int NUMREAL = 21;
  public static final int error = 1;
  public static final int POINTER = 6;
  public static final int ABRECOR = 14;
  public static final int INTEGER = 2;
  public static final int REAL = 3;
  public static final int TO = 7;
  public static final int ARRAY = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "REAL",
  "CHAR",
  "BOOLEAN",
  "POINTER",
  "TO",
  "ARRAY",
  "OF",
  "PROCEDURE",
  "CARACTER",
  "ABREPAR",
  "CIERRAPAR",
  "ABRECOR",
  "CIERRACOR",
  "DOSPUNTOS",
  "COMA",
  "PTOYCOMA",
  "ID",
  "NUM",
  "NUMREAL"
  };
}

