
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package pl5;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int NUM = 12;
  public static final int POW = 8;
  public static final int MENOS = 4;
  public static final int UMENOS = 11;
  public static final int POR = 5;
  public static final int ENTRE = 6;
  public static final int ABREPAR = 9;
  public static final int EOF = 0;
  public static final int MAS = 3;
  public static final int CIERRAPAR = 10;
  public static final int MODULO = 7;
  public static final int error = 1;
  public static final int PTOYCOMA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTOYCOMA",
  "MAS",
  "MENOS",
  "POR",
  "ENTRE",
  "MODULO",
  "POW",
  "ABREPAR",
  "CIERRAPAR",
  "UMENOS",
  "NUM"
  };
}

