
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package procesadores;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int END_STRUCT = 4;
  public static final int END_BLOCK = 6;
  public static final int POW = 31;
  public static final int STRING_LITERAL = 45;
  public static final int FUNCTION = 11;
  public static final int MULT = 30;
  public static final int CHAR = 14;
  public static final int CHAR_LITERAL = 44;
  public static final int NOT_EQUAL = 21;
  public static final int GREATER = 19;
  public static final int NUM_INT = 42;
  public static final int INT = 12;
  public static final int LESS = 18;
  public static final int MINUS = 27;
  public static final int AND = 24;
  public static final int CLOSE_PAR = 8;
  public static final int OPEN_PAR = 7;
  public static final int OR = 25;
  public static final int COMMA = 35;
  public static final int BOOL = 16;
  public static final int OPEN_BRACKETS = 9;
  public static final int DIV = 28;
  public static final int LESS_EQUAL = 22;
  public static final int PLUS = 26;
  public static final int ASSIGN = 17;
  public static final int IF = 33;
  public static final int ID = 46;
  public static final int EOF = 0;
  public static final int RETURN = 39;
  public static final int EQUAL = 20;
  public static final int TRUE = 37;
  public static final int GREATER_EQUAL = 23;
  public static final int error = 1;
  public static final int MOD = 29;
  public static final int INIT_BLOCK = 5;
  public static final int REAL = 13;
  public static final int NUM_REAL = 43;
  public static final int ELSE = 34;
  public static final int READ = 40;
  public static final int POINT = 36;
  public static final int WHILE = 32;
  public static final int END_INSTR = 2;
  public static final int CLOSE_BRACKETS = 10;
  public static final int STRING = 15;
  public static final int FALSE = 38;
  public static final int STRUCT = 3;
  public static final int PRINT = 41;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "END_INSTR",
  "STRUCT",
  "END_STRUCT",
  "INIT_BLOCK",
  "END_BLOCK",
  "OPEN_PAR",
  "CLOSE_PAR",
  "OPEN_BRACKETS",
  "CLOSE_BRACKETS",
  "FUNCTION",
  "INT",
  "REAL",
  "CHAR",
  "STRING",
  "BOOL",
  "ASSIGN",
  "LESS",
  "GREATER",
  "EQUAL",
  "NOT_EQUAL",
  "LESS_EQUAL",
  "GREATER_EQUAL",
  "AND",
  "OR",
  "PLUS",
  "MINUS",
  "DIV",
  "MOD",
  "MULT",
  "POW",
  "WHILE",
  "IF",
  "ELSE",
  "COMMA",
  "POINT",
  "TRUE",
  "FALSE",
  "RETURN",
  "READ",
  "PRINT",
  "NUM_INT",
  "NUM_REAL",
  "CHAR_LITERAL",
  "STRING_LITERAL",
  "ID"
  };
}

